# config/database.yml

default: &default
  adapter: postgresql
  encod ing: unicode
  username: rafael
  password: 41723
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: <%= ENV['DB_PORT'] || 5432 %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DB_NAME_DEVELOPMENT'] || 'blog_development' %>

test:
  <<: *default
  database: <%= ENV['DB_NAME_TEST'] || 'blog_test' %>

production:
  primary:
    <<: *default
    database: <%= ENV["DATABASE_NAME"] %>
    username: rafael
    password: 41723
    host: <%= ENV["DATABASE_HOST"] %>
    port: <%= ENV.fetch("DATABASE_PORT", 5432) %>
    

  queue:
    <<: *default
    database: blog_production_queue